# config/members/justus.yaml
member: justus
model: o3-mini

prompts:
  original: src/prompts/CTF/system_prompt
  prompt-charlie: config/custom_prompts/charlie_instructional.txt
  prompt-juan: config/custom_prompts/juan_instructional.txt
  prompt-justus: config/custom_prompts/justus_poisoned.txt
  prompt-miguel-i: config/custom_prompts/miguel_instructional.txt
  prompt-miguel-p: config/custom_prompts/miguel_poisoned.txt
  prompt-ryan: config/custom_prompts/ryan_instructional.txt